In [13]:
print("Hello AI Journey!")

Hello AI Journey!


In [14]:
nilai = [80, 75, 90, 60, 85]

In [15]:
def rata_rata(data):
    return sum(data) / len(data)

print(rata_rata(nilai))

78.0


In [16]:
for n in nilai:
    if n >= 75:
        print(n, "LULUS")
    else:
        print(n, "TIDAK LULUS")

80 LULUS
75 LULUS
90 LULUS
60 TIDAK LULUS
85 LULUS


CHALLENGE 1

In [17]:
nilai = [80, 75, 90, 60, 85]

def evaluasi_nilai(data):
    hasil = []
    for n in data:
        if n >= 75:
            hasil.append("LULUS")
        else:
            hasil.append("TIDAK LULUS")
    return hasil

print(evaluasi_nilai(nilai))

['LULUS', 'LULUS', 'LULUS', 'TIDAK LULUS', 'LULUS']


CHALENGE 2 (Refactor)  
`def cek_kelulusan(data):
 pass`


In [18]:
def cek_kelulusan(data):
    pass
    return ["LULUS" if n >= 75 else "TIDAK LULUS" for n in data]

## DAY 2

In [19]:
import numpy as np

nilai = np.array([80, 75, 90, 60, 85])
print(nilai)
print(type(nilai))


[80 75 90 60 85]
<class 'numpy.ndarray'>


In [20]:
print(nilai + 5)


[85 80 95 65 90]


In [21]:
print("Rata-rata:", np.mean(nilai))
print("Standar deviasi:", np.std(nilai))
print("Nilai max:", np.max(nilai))
print("Nilai min:", np.min(nilai))


Rata-rata: 78.0
Standar deviasi: 10.295630140987
Nilai max: 90
Nilai min: 60


In [22]:
lulus = nilai[nilai >= 75]
print(lulus)


[80 75 90 85]


## DAY 3

In [23]:
import pandas as pd

In [24]:
data = {
    "nama": ["Andi", "Budi", "Citra", "Dewi"],
    "nilai": [80, 70, 90, 60],
    "kelas": ["A", "A", "B", "B"]
}

df = pd.DataFrame(data)
df


nama  nilai kelas
0   Andi     80     A
1   Budi     70     A
2  Citra     90     B
3   Dewi     60     B

In [25]:
df_lulus = df[df["nilai"] >= 75]
df_lulus


nama  nilai kelas
0   Andi     80     A
2  Citra     90     B

In [26]:
df["nilai"].mean()


np.float64(75.0)

In [27]:
df.groupby("kelas")["nilai"].mean()


kelas
A    75.0
B    75.0
Name: nilai, dtype: float64

In [28]:
df["status"] = df["nilai"].apply(
    lambda x: "LULUS" if x >= 75 else "TIDAK LULUS"
)

df


nama  nilai kelas       status
0   Andi     80     A        LULUS
1   Budi     70     A  TIDAK LULUS
2  Citra     90     B        LULUS
3   Dewi     60     B  TIDAK LULUS